[package]
name = "funring"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
gtk = "0.18.1"
mpris = "2.0.1"
tray-icon = "0.10.0"
